CREATE DATABASE IF NOT EXISTS school;
CREATE TABLE IF NOT EXISTS alunos (
  matricula SERIAL PRIMARY KEY,
  cpf INTEGER UNIQUE NOT NULL,
  nome TEXT NOT NULL,
  responsavel TEXT
);
CREATE TABLE IF NOT EXISTS professores(
  id SERIAL PRIMARY KEY,
  cpf INTEGER UNIQUE NOT NULL,
  nome TEXT NOT NULL,
  materia TEXT
);
